development:
  languages: cpp;java;python;ruby

test:
  languages: cpp;java;python;ruby

production:
  languages: cpp;java;python;ruby
  compiled_languages: cpp;java
  input_file_pattern: input.*.txt
  output_file_pattern: output.*.txt
  sync: rsync -azv -e ssh
  files_root: /home/vagrant/grader_root
  sync_to: sets
  runs_dir: runs
  sandbox_dir: /sandbox

  file_basename: program
  extension_cpp: cpp
  extension_java: java
  extension_python: py
  extension_ruby: rb

  compile_cpp: g++ %s -o %s -O2
  compile_java: gcj --main=program %s -o %s

  runner_cpp: runner_fork.rb
  runner_java: runner_fork.rb
  runner_python: runner_fork.rb
  runner_ruby: runner_fork.rb

  exec_cpp: ./program
  exec_java: ./program
  exec_python: /usr/bin/python2.7 ./program.py
  exec_ruby: /usr/bin/ruby ./program.rb
  # Used to run Python unit tests. May be generalized in the future when
  # unit tests are added for more languages
  exec_python_unit: /usr/bin/python2.7 ./wrapper_code.py

  min_memory_limit_kb: 4096
  max_memory_limit_kb: 262144
  max_exec_time_ms: 5000
  max_processes: 50

  docker_container_user: grader
  docker_image_name: grader
