---
- hosts: all
  sudo: no

  vars:
    app_root: /home/grader/applications/grader
    app_name: codemarathon_grader
    git_repo: git@github.com:antonrd/codemarathon-grader.git
    server_name: grader.codemarathon.com
    ruby_version: 2.2.2

  roles:
    - install
    - config
    - restart

# Additional tasks to perform manually:
# create grader user in sudo/admin group
  # sudo adduser grader
  # sudo usermod -a -G admin userName
  # sudo usermod -a -G sudo userName
  # create ~/.ssh/authorized_keys with public key
  # sudo visudo -f /etc/sudoers.d/myOverrides and add 'grader  ALL=NOPASSWD: ALL' to not ask for password on sudo
# change /etc/hosts to make sendmail work fast

# Locally fix ~/.ssh/config to do forwarding of keys:
# Host codemarathon
#    ...
#    ForwardAgent yes

# Start/restart upstart in a more clever way, make it more robust.
